### ISSUE TITLE
A problem occurred evaluating project ':app'.

### ISSUE THREAD

**Issue by Khansaab-code** [codinginflow/ImageSearchApp#3]

**Comment by dennisrufigill** [comment]
Even I faced the same issue. You must be using any inappropriate dependency or deprecated term in your build.gradle(App-Module).

**Comment by Kirankj1724** [comment]
You should have figured this out by now, but just as a note to users : 

I believe this is due to not declaring the **UNSPLASH_ACCESS_KEY** in gradle file.
This is explained at the end of the video 1 in the playlist on youtube (link from readme).

**Comment by klaus19** [comment]
> 
> 
> You should have figured this out by now, but just as a note to users :
> 
> I believe this is due to not declaring the **UNSPLASH_ACCESS_KEY** in gradle file. This is explained at the end of the video 1 in the playlist on youtube (link from readme).

I have solved this error. You just need to create your API KEY and paste it in the gradle.properties file and sync. The error will be removed.

**Comment by codinginflow** [comment]
Thank you for clarifying!

**Comment by klaus19** [comment]
OMG! Thanx for you reply mate! :) Right now at this moment, I am watching
YouTube video series about this :)

Thanx for this tutorial. You are talented.

**Comment by klaus19** [comment]
> 
> 
> Thank you for clarifying!

You are not even giving an access to push and remove the issue! Why ? if you want to followed by many people , you need to open minded.

**Comment by codinginflow** [comment]
> > Thank you for clarifying!
> 
> You are not even giving an access to push and remove the issue! Why ? if you want to followed by many people , you need to open minded.

Because the code should be in sync with the tutorial videos (which works)

**Comment by codinginflow** [comment]
Problem solved by following the tutorial instructions.
